### ISSUE TITLE
No x86_64 abi

### ISSUE THREAD

**Issue by dennisvandalen** [DimaArts/openjpegAndroid#1]
Awesome work on the example app and porting the OpenJpeg library.

Is it possible to add the x86_64 .so? 

I've tried compiling OpenJpeg myself but it didn't work out. Maybe you can add the build instructions?

**Comment by DimaArts** [comment]
Android part of official OpenJpeg has not been developed for a long time. I added support to JNI. In the near future I will compile x86_64 and add to the project. Thanks for the feedback.

**Comment by dennisvandalen** [comment]
Thanks for the reply @DimaArts. Can you tell me where to find the Android part of official OpenJpeg? And maybe make a small howto on how to compile it (or maybe link your gradle/makefiles)?

**Comment by DimaArts** [comment]
You can find source in https://github.com/uclouvain/openjpeg. Folder openjpeg/wrapping/java/. But it is very old and so you can not compile this without changes. It is for java, but you can use it for android. My library contains small fixes for use it.

**Comment by dennisvandalen** [comment]
Okay, I had already found that. It would be awesome if you could commit your changes to make it work 🎉

**Comment by DimaArts** [comment]
I'm not a professional in C ++ developmer. I had to change the structure of the project and add some libraries for successful compilation. In the original version, the parameters were passed through the object, in my through a string, analog command line. I can grant access to the bitbucket repository for you.

**Comment by dennisvandalen** [comment]
That'd great. I am https://bitbucket.org/dvandalen/

**Comment by DimaArts** [comment]
I'll add it when I get back from work. Source on my personal computer.
