### ISSUE TITLE
Can you provide the source code used to compile for Java?

### ISSUE THREAD

**Issue by ElMostafaIdrassi** [DimaArts/openjpegAndroid#2]
First of all thank you for the effort of providing ARM builds of the OpenJPEG Jni libs! Not only is the JNI part of the OpenJPEG project outdated, but to make it work is a hell of a mess!

Second I'm sorry for opening an issue for this, but it is the only way to get in touch with you...

Can you please provide the modified source code that enabled you to build the JNI part, or at least some hints on how to make it work? I am a bit struggling on this...

**Comment by DimaArts** [comment]
Hello. Thank you for your interest in this library and for feedback. Could you give me a Bitbucket account so that I can give you access to the source code of the modified OpenJpeg library.

**Comment by ElMostafaIdrassi** [comment]
Thank you for your reply! Here is my bitbucket account : https://bitbucket.org/MostafaId/ . Much obliged

**Comment by DimaArts** [comment]
Access granted
