### ISSUE TITLE
Error occurred : java.io.FileNotFoundException: if change package name or path

### ISSUE THREAD

**Issue by GovindaPaliwal** [DimaArts/openjpegAndroid#3]
Please check below error.
Error : java.io.FileNotFoundException: /data/user/0/com.temp.myname/files/temp.png (No such file or directory)

**Comment by DimaArts** [comment]
Hi. Thank you for feedback. Are you sure that the file is exists? Check it:
File file = new File(filePath);
if(file.exists())
Is this error in the decoding or encoding?

**Comment by GovindaPaliwal** [comment]
Hi.
Yes file.exists() return true. everything work fine with your code. but when i use in my code its gives the error. 

But Now it's working after Invalidate Caches / Restart android studio but sometimes it return black image .

Can you share build JNI version of OpenJpeg

Thank you

**Comment by DimaArts** [comment]
JNI source code in a private bitbucket repository, if you have bitbucket account i can add permissions to this repository. And I will update version of the OpenJpeg and check again how it works. Provide more information about the problem if you can (device, android version, abi).

**Comment by GovindaPaliwal** [comment]
Yes , sure. Will check and late you know if there is any problem.
BTW my bitbucket account URL is https://bitbucket.org/gpfreetech

**Comment by DimaArts** [comment]
I sent an invitation to gpfreetech@gmail.com, but I don’t know what mail was used. Bitbucket requires mail. 
Bitbucket says:
In order to improve user privacy, we have made changes to Bitbucket Cloud invitations. You must now enter an email address to add users who don’t currently have access to this account.

**Comment by GovindaPaliwal** [comment]
Hey, i got your invitation. Thanks
